#!/bin/bash

# install necessary packages
sudo apt install -y zsh mtr-tiny tcpdump vim git htop iptraf-ng netcat-openbsd pv lzop tmux 

# install packages for youcompleteme
sudo apt install -y build-essential cmake python3-dev

# clonin vundle for vim
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

# install youcompleteme
# /.vim/bundle/YouCompleteMe/./install.py --clang-completer

